model: 'EnzymeCAGE'
interaction_method: 'geo-enhanced-interaction'
rxn_inner_interaction: True
pocket_inner_interaction: True
use_prods_info: False
use_structure: True
use_drfp: True
use_esm: True
esm_model: ESM-C_600M
batch_size: 256
model_list: ['epoch_19.pth']

data_path: ./dataset/external-test-set/p450/test_P450.csv
ckpt_dir: ./checkpoints/pretrain/seed_42/

### general feature path 
rxn_fp: dataset/external-test-set/p450/feature/reaction/drfp/rxn2fp.pkl
mol_conformation: dataset/external-test-set/p450/feature/reaction/molecule_conformation
reaction_center: dataset/external-test-set/p450/feature/reaction/reacting_center/reacting_center.pkl
protein_gvp_feat: dataset/external-test-set/p450/feature/protein/gvp_feature/gvp_protein_feature.pt
esm_mean_feature: dataset/external-test-set/p450/feature/protein/ESM-C_600M/protein_level/seq2feature.pkl
esm_node_feature: dataset/external-test-set/p450/feature/protein/ESM-C_600M/pocket_node_feature/esm_node_feature.pt
