
gpu: 4
data_version: 'V9'
recall_method: 'selenzyme'

model: 'gvp-painn'
# interaction_method: 'pairformer'
interaction_method: 'cross-attention'
data_split_by: 'all'
# data_split_by: 'toy'
data_dir: '/home/liuy/code/SynBio/enzyme-rxn-prediction/dataset/baseline/V9/'
# save_dir: '/mnt/nas/ai-algorithm-data/liuyong/code/SynBio/enzyme-rxn-prediction/checkpoints/'
# ckpt_dir: '/mnt/nas/ai-algorithm-data/liuyong/code/SynBio/enzyme-rxn-prediction/checkpoints/V9/split_by_both/gvp_gat'

use_gvppainn: True
use_drfp: True
use_esm: True

batch_size: 128
label_column_name: 'Label'

auto_load_data: False

# train_path: '/home/liuy/data/SynBio/enzyme-reaction-pairs/training/toy/test.csv'
# valid_path: '/home/liuy/data/SynBio/enzyme-reaction-pairs/training/toy/test.csv'
# test_path: '/home/liuy/data/SynBio/enzyme-reaction-pairs/training/toy/test.csv'
# ckpt_dir: '/home/liuy/code/SynBio/enzyme-rxn-prediction/checkpoints/toy'

# train_path: '/mnt/nas/ai-algorithm-data/liuyong/dataset/SynBio/enzyme-reaction-pairs/v9/remove_no_ec/with_atom_limits/train.csv'
# valid_path: '/mnt/nas/ai-algorithm-data/liuyong/dataset/SynBio/enzyme-reaction-pairs/v9/remove_no_ec/with_atom_limits/test.csv'
# test_path: '/mnt/nas/ai-algorithm-data/liuyong/dataset/SynBio/enzyme-reaction-pairs/v9/remove_no_ec/with_atom_limits/test.csv'
# ckpt_dir: '/mnt/nas/ai-algorithm-data/liuyong/code/SynBio/enzyme-rxn-prediction/checkpoints/V9/no_ec_rxns/esm_gvppainn_drfp_cross-attn_lr3e-4_decay_bn'

# train_path: '/home/liuy/data/SynBio/enzyme-reaction-pairs/training/v9/eval_new_enzymes/v3/train.csv'
# valid_path: '/home/liuy/data/SynBio/enzyme-reaction-pairs/training/v9/eval_new_enzymes/v3/test.csv'
# test_path: '/home/liuy/data/SynBio/enzyme-reaction-pairs/training/v9/eval_new_enzymes/v3/test.csv'
# ckpt_dir: '/home/liuy/code/SynBio/enzyme-rxn-prediction/checkpoints/V9/eval_new_enzymes/v3/esm_gvppainn_drfp_cross-attn_lr1e-4_decay-0.95'

train_path: '/home/liuy/data/SynBio/enzyme-reaction-pairs/training/v9/remove_no_ec/with_atom_limits/train.csv'
valid_path: '/home/liuy/data/SynBio/enzyme-reaction-pairs/training/v9/remove_no_ec/with_atom_limits/test.csv'
test_path: '/home/liuy/data/SynBio/enzyme-reaction-pairs/training/v9/remove_no_ec/with_atom_limits/test.csv'
ckpt_dir: '/home/liuy/code/SynBio/enzyme-rxn-prediction/checkpoints/V9/no_ec_rxns/esm_gvppainn_drfp_cross-attn_lr1e-4_decay-0.95'

