
gpu: 1
data_version: 'V9'
recall_method: 'selenzyme'

model: 'gvp-gat'
data_split_by: 'all'
data_dir: '/mnt/nas/ai-algorithm-data/liuyong/code/SynBio/enzyme-rxn-prediction/dataset/baseline/V9/'
# save_dir: '/mnt/nas/ai-algorithm-data/liuyong/code/SynBio/enzyme-rxn-prediction/checkpoints/'
# ckpt_dir: '/mnt/nas/ai-algorithm-data/liuyong/code/SynBio/enzyme-rxn-prediction/checkpoints/V9/split_by_both/gvp_gat'

use_esm: True
use_gvp: False
use_unimol: False
use_drfp: True
use_rxn_gat: False


# esm+gat
# batch_size: 1024

# # esm+gvp+gat
# batch_size: 256

# # esm+drfp
batch_size: 512

auto_load_data: False

# train_path: '/mnt/nas/ai-algorithm-data/liuyong/code/SynBio/enzyme-rxn-prediction/dataset/baseline/V9/split_all/csv/train.csv'
# valid_path: '/mnt/nas/ai-algorithm-data/liuyong/code/SynBio/enzyme-rxn-prediction/dataset/recruit_infer/V9/infer_data_selenzyme.csv'
# test_path: '/mnt/nas/ai-algorithm-data/liuyong/code/SynBio/enzyme-rxn-prediction/dataset/recruit_infer/V9/infer_data_selenzyme.csv'

# train_path: '/mnt/nas/ai-algorithm-data/liuyong/dataset/SynBio/enzyme-reaction-pairs/v9/remove_no_ec/train.csv'
# valid_path: '/mnt/nas/ai-algorithm-data/liuyong/dataset/SynBio/enzyme-reaction-pairs/v9/remove_no_ec/test.csv'
# test_path: '/mnt/nas/ai-algorithm-data/liuyong/dataset/SynBio/enzyme-reaction-pairs/v9/remove_no_ec/test.csv'
# ckpt_dir: '/mnt/nas/ai-algorithm-data/liuyong/code/SynBio/enzyme-rxn-prediction/checkpoints/V9/no_ec_rxns/esm_drfp_gat'

# train_path: '/mnt/nas/ai-algorithm-data/liuyong/dataset/SynBio/enzyme-reaction-pairs/v9/remove_no_ec/with_atom_limits/train.csv'
# valid_path: '/mnt/nas/ai-algorithm-data/liuyong/dataset/SynBio/enzyme-reaction-pairs/v9/remove_no_ec/with_atom_limits/test.csv'
# test_path: '/mnt/nas/ai-algorithm-data/liuyong/dataset/SynBio/enzyme-reaction-pairs/v9/remove_no_ec/with_atom_limits/test.csv'
# ckpt_dir: '/mnt/nas/ai-algorithm-data/liuyong/code/SynBio/enzyme-rxn-prediction/checkpoints/V9/no_ec_rxns/esm_gvp_drfp_gat'
# ckpt_dir: '/mnt/nas/ai-algorithm-data/liuyong/code/SynBio/enzyme-rxn-prediction/checkpoints/V9/no_ec_rxns/esm_drfp'

# train_path: '/mnt/nas/ai-algorithm-data/liuyong/dataset/SynBio/enzyme-reaction-pairs/v9/single_elem_ec/train.csv'
# valid_path: '/mnt/nas/ai-algorithm-data/liuyong/dataset/SynBio/enzyme-reaction-pairs/v9/single_elem_ec/test.csv'
# test_path: '/mnt/nas/ai-algorithm-data/liuyong/dataset/SynBio/enzyme-reaction-pairs/v9/single_elem_ec/test.csv'
# ckpt_dir: '/mnt/nas/ai-algorithm-data/liuyong/code/SynBio/enzyme-rxn-prediction/checkpoints/V9/single_elem_ec/esm_drfp'

train_path: '/mnt/nas/ai-algorithm-data/liuyong/dataset/SynBio/enzyme-reaction-pairs/v9/remove_no_ec/with_atom_limits_proevi-1/train.csv'
valid_path: '/mnt/nas/ai-algorithm-data/liuyong/dataset/SynBio/enzyme-reaction-pairs/v9/remove_no_ec/with_atom_limits_proevi-1/test.csv'
test_path: '/mnt/nas/ai-algorithm-data/liuyong/dataset/SynBio/enzyme-reaction-pairs/v9/remove_no_ec/with_atom_limits_proevi-1/test.csv'
ckpt_dir: '/mnt/nas/ai-algorithm-data/liuyong/code/SynBio/enzyme-rxn-prediction/checkpoints/V9/no_ec_rxns/esm_drfp_cross-attn_bn_proevi-1'

label_column_name: 'Label'

