model: 'EnzymeCAGE'
interaction_method: 'geo-enhanced-interaction'
rxn_inner_interaction: True
pocket_inner_interaction: True
use_prods_info: False
use_structure: True
use_drfp: True
use_esm: True
batch_size: 16
predict_mode: 'only_best'

data_path: dataset/toy-data/test.csv
ckpt_dir: checkpoints/unseen-enzymes/seed_42/


# feature
rxn_fp: dataset/toy-data/feature/reaction/drfp/rxn2fp.pkl
protein_gvp_feat: dataset/toy-data/feature/protein/gvp_feature/gvp_protein_feature.pt
esm_mean_feature: dataset/toy-data/feature/protein/esm2_t33_650M_UR50D/protein_level/seq2feature.pkl
esm_node_feature: dataset/toy-data/feature/protein/esm2_t33_650M_UR50D/pocket_node_feature/esm_node_feature.pt
mol_conformation: dataset/feature/reaction/molecule_conformation
reaction_center: dataset/toy-data/feature/reaction/reacting_center/reacting_center.pkl
