model: EnzymeCAGE
interaction_method: geo-enhanced-interaction
rxn_inner_interaction: True
pocket_inner_interaction: True

use_prods_info: False
use_structure: True
use_drfp: True
use_esm: True

seed: 42
num_epochs: 2
lr_init: 0.0003
batch_size: 16
use_gradient_accumulation: False

label_column_name: 'Label'

train_path: dataset/testing/test.csv
valid_path: dataset/testing/test.csv
test_path: dataset/testing/test.csv
ckpt_dir: checkpoints/toy

pretrain_model: null

### feature
rxn_fp: dataset/testing/feature/reaction/drfp/rxn2fp.pkl
protein_gvp_feat: dataset/testing/feature/protein/gvp_feature/gvp_protein_feature.pt
esm_mean_feature: dataset/testing/feature/protein/esm2_t33_650M_UR50D/protein_level/seq2feature.pkl
esm_node_feature: dataset/testing/feature/protein/esm2_t33_650M_UR50D/pocket_node_feature/esm_node_feature.pt
mol_conformation: dataset/testing/feature/reaction/molecule_conformation
reaction_center: dataset/testing/feature/reaction/reacting_center/reacting_center.pkl
