model: EnzymeCAGE
interaction_method: geo-enhanced-interaction
rxn_inner_interaction: True
pocket_inner_interaction: True

use_prods_info: False
use_structure: True
use_drfp: True
use_esm: True
esm_model: ESM-C_600M

seed: 40
num_epochs: 20
lr_init: 0.0003
batch_size: 256
use_gradient_accumulation: False
weight_col: null
label_column_name: Label

train_path: dataset/training/train.csv
valid_path: dataset/training/valid.csv
test_path: dataset/training/valid.csv
ckpt_dir: checkpoints/pretrain/seed_40

pretrain_model: null

### general feature path 
rxn_fp: dataset/RHEA/2025-02-05/feature/reaction/drfp/rxn2fp.pkl
protein_gvp_feat: dataset/RHEA/2025-02-05/feature/protein/gvp_feature/gvp_protein_feature.pt
esm_mean_feature: dataset/RHEA/2025-02-05/feature/protein/ESM-C_600M/protein_level/seq2feature.pkl
esm_node_feature: dataset/RHEA/2025-02-05/feature/protein/ESM-C_600M/pocket_node_feature/esm_node_feature.pt
mol_conformation: dataset/RHEA/2025-02-05/feature/reaction/molecule_conformation
reaction_center: dataset/RHEA/2025-02-05/feature/reaction/reacting_center/reacting_center.pkl