model: 'EnzymeCAGE'

interaction_method: 'geo-enhanced-interaction'
rxn_inner_interaction: True
pocket_inner_interaction: True

use_prods_info: False
use_structure: True
use_drfp: True
use_esm: True

seed: 42
num_epochs: 2
lr_init: 0.0003
batch_size: 16
use_gradient_accumulation: False

label_column_name: 'Label'

train_path: '/home/liuy/data/SynBio/enzyme-reaction-pairs/training/toy/test.csv'
valid_path: '/home/liuy/data/SynBio/enzyme-reaction-pairs/training/toy/test.csv'
test_path: '/home/liuy/data/SynBio/enzyme-reaction-pairs/training/toy/test.csv'
ckpt_dir: '/home/liuy/code/SynBio/EnzymeCAGE/checkpoints/toy'

pretrain_model: null

### general feature path 
rxn_fp: /home/liuy/data/SynBio/enzyme-reaction-pairs/training/toy/feature/reaction/drfp/rxn2fp.pkl
# protein_gvp_feat: /home/liuy/data/SynBio/enzyme-reaction-pairs/feature/gvp_torchdrug_feature/protein_pocket_8A_new.pt
protein_gvp_feat: /home/liuy/data/SynBio/enzyme-reaction-pairs/training/toy/gvp_protein_feature_toy.pt
esm_mean_feature: /home/liuy/data/SynBio/enzyme-reaction-pairs/feature/esm2_t33_650M_UR50D/protein_level/seq2feature.pkl
# esm_node_feature: /home/liuy/data/SynBio/enzyme-reaction-pairs/feature/esm2_t33_650M_UR50D/node_level/esm_pocket_node_feature.pt
esm_node_feature: /home/liuy/data/SynBio/enzyme-reaction-pairs/training/toy/esm_node_feature.pt
# mol_conformation: /home/liuy/data/SynBio/enzyme-reaction-pairs/others/molecule_conformation/sdf
mol_conformation: /home/liuy/data/SynBio/enzyme-reaction-pairs/training/toy/feature/reaction/molecule_conformation
# reaction_center: /home/liuy/data/SynBio/enzyme-reaction-pairs/others/reacting_center/reacting_center.pkl
reaction_center: /home/liuy/data/SynBio/enzyme-reaction-pairs/training/toy/feature/reaction/reacting_center/reacting_center.pkl
